name: Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        AWS_DEFAULT_REGION: ap-northeast-2  # 원하는 AWS 리전 지정
      run: |
        docker build -t $ECR_REGISTRY/$REPO_NAME:latest .
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login --username AWS --password-stdin $ECR_REGISTRY
        docker push $ECR_REGISTRY/$REPO_NAME:latest

